site_name: Vanessa Automation
theme:
  name: material
  language: 'ru'
  logo: 'assets/images/logo.png'
  favicon: 'assets/images/logo.png'
  palette:
    primary: 'white'
    accent: 'red'
  feature:
    tabs: true
extra:
  search:
    language: 'en, ru'
  social:
    - type: 'github'
      link: 'https://github.com/Pr-Mex/vanessa-automation'
    - type: 'telegram'
      link: 'https://t.me/VanessaAutomation'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
site_url: 'https://pr-mex.github.io/vanessa-automation'
repo_name: 'pr-mex/vanessa-automation'
repo_url: 'https://github.com/pr-mex/vanessa-automation'
edit_uri: 'edit/develop/docs'