# language: ru
# encoding: utf-8
#parent uf:
@UF10_Запуск_VA
#parent ua:
@UA35_запускать_интерактивно

@IgnoreOn82Builds
@IgnoreOnOFBuilds
@IgnoreOnWeb
@IgnoreOn836
@IgnoreOn837
@IgnoreOn838
@IgnoreOn839
@tree

Функционал: Открытие VA для записи автодоков.
 


Сценарий: Открытие VA для записи автодоков как клиент тестирования
	Дано Я закрыл все окна клиентского приложения
	И я закрываю сеанс TESTCLIENT
	Когда я запускаю служебный сеанс TestClient с ключом TestManager в той же базе
	
	Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
	
	
	И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ЗаписьАвтодоков/ДляЗаписиАвтодоков01"

	И я перехожу к закладке с именем "ГруппаНастройки"
	И я перехожу к закладке с именем "СтраницаВыполнениеСценариев"
	И в поле с именем 'ТаймаутДляАсинхронныхШагов' я ввожу текст '80'
	
	И я перехожу к закладке с именем "ГруппаНастройки"
	И я перехожу к закладке с именем "СтраницаСервисОсновные"
	И я устанавливаю флаг с именем 'ДелатьЛогВыполненияСценариевВЖР'
	
	И я перехожу к закладке с именем "СтраницаАвтоИнструкции"
	И я разворачиваю группу с именем "ГруппаSikuliXServer"
	И я устанавливаю флаг с именем 'ИспользоватьSikuliXСервер'
	И пауза 2
	И я нажимаю на кнопку с именем 'КаталогиСкриптовSikuliXПоУмолчанию'

	И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
	И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient

	//И я выбираю пункт контекстного меню с именем 'ДеревоТестовКонтекстноеМенюСвернутьДоСценариев' на элементе формы с именем "ДеревоТестов"

	И я перехожу к закладке "Служебная"
	И я нажимаю на кнопку 'Развернуть все строки дерева служебный'
	И я перехожу к закладке "Запуск сценариев"
	
	Тогда таблица "ДеревоТестов" содержит строки
		| 'Наименование'                                                                                                            | 'Имя процедуры'                                                                           | 'Адрес в файле'                                                                                                                 | 'Статус'  | 'Снипет'                                                                                    | 'Обработка'                                                                                                             | '№'  |
		| 'ДляЗаписиАвтодоков01.feature'                                                                                            | ''                                                                                        | 'C:\Commons\rep\vanessa-automation\features\Support\Templates\ЗаписьАвтодоков\ДляЗаписиАвтодоков01.feature'                     | ''        | ''                                                                                          | ''                                                                                                                      | ''   |
		| 'ДляЗаписиАвтодоков01'                                                                                                    | ''                                                                                        | 'C:\Commons\rep\vanessa-automation\features\Support\Templates\ЗаписьАвтодоков\ДляЗаписиАвтодоков01.feature'                     | ''        | ''                                                                                          | ''                                                                                                                      | '1'  |
		| 'ДляЗаписиАвтодоков01'                                                                                                    | ''                                                                                        | 'C:\Commons\rep\vanessa-automation\features\Support\Templates\ЗаписьАвтодоков\ДляЗаписиАвтодоков01.feature:14'                  | 'Success' | ''                                                                                          | ''                                                                                                                      | '2'  |
		| 'Дано Я открываю Vanessa-Automation в TestClient для записи автодокументации'                                             | ''                                                                                        | '     C:\Commons\rep\vanessa-automation\features\Support\Templates\ЗаписьАвтодоков\ДляЗаписиАвтодоков01.feature:15'             | ''        | ''                                                                                          | 'C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature' | '3'  |
		| 'И я устанавливаю текущему сеансу заголовок приложения "Управляющий сеанс"'                                               | 'ЯУстанавливаюТекущемуСеансуЗаголовокПриложения'                                          | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:18' | 'Success' | 'ЯУстанавливаюТекущемуСеансуЗаголовокПриложения(Парам01)'                                   | 'C:\Commons\rep\vanessa-automation\features\Libraries\VB\step_definitions\УстановкаСистемныхПараметров.epf'             | '4'  |
		| 'И я запоминаю строку "ДопПараметр" в переменную "ЗначениеПараметра"'                                                     | 'ЯЗапоминаюСтрокуВПеременную'                                                             | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:19' | 'Success' | 'ЯЗапоминаюСтрокуВПеременную(Парам01,Парам02)'                                              | 'C:\Commons\rep\vanessa-automation\features\Libraries\ВстроенныйЯзык\ВстроенныйЯзык.epf'                                | '5'  |
		| 'Дано Я открыл новый сеанс TestClient как TestManager или подключил уже существующий без загрузки настроек'               | 'ЯОткрылНовыйСеансTestClientКакTestManagerИлиПодключилУжеСуществующийБезЗагрузкиНастроек' | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:21' | ''        | 'ЯОткрылНовыйСеансTestClientКакTestManagerИлиПодключилУжеСуществующийБезЗагрузкиНастроек()' | 'C:\Commons\rep\vanessa-automation\features\Libraries\TestClients\step_definitions\РаботаСTestClient.epf'               | '7'  |
		| 'Иначе'                                                                                                                   | ''                                                                                        | ''                                                                                                                              | ''        | ''                                                                                          | ''                                                                                                                      | '8'  |
		| 'Дано Я открыл новый сеанс TestClient или подключил уже существующий без загрузки настроек'                               | 'ЯОткрылНовыйСеансTestClientИлиПодключилУжеСуществующийБезЗагрузкиНастроек'               | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:23' | 'Success' | 'ЯОткрылНовыйСеансTestClientИлиПодключилУжеСуществующийБезЗагрузкиНастроек()'               | 'C:\Commons\rep\vanessa-automation\features\Libraries\TestClients\step_definitions\РаботаСTestClient.epf'               | '9'  |
		| 'И Я закрыл все окна клиентского приложения'                                                                              | 'ЯЗакрылВсеОкнаКлиентскогоПриложения'                                                     | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:24' | 'Success' | 'ЯЗакрылВсеОкнаКлиентскогоПриложения()'                                                     | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '10' |
		| 'И Я открываю VanessaAutomation в режиме TestClient \'VAEditor\''                                                         | ''                                                                                        | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:25' | ''        | ''                                                                                          | 'C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature'                     | '11' |
		| 'Дано я запоминаю строку \'VAEditor\' в переменную "ЗначениеПараметра"'                                                   | 'ЯЗапоминаюСтрокуВПеременную'                                                             | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:20'                     | 'Success' | 'ЯЗапоминаюСтрокуВПеременную(Парам01,Парам02)'                                              | 'C:\Commons\rep\vanessa-automation\features\Libraries\ВстроенныйЯзык\ВстроенныйЯзык.epf'                                | '12' |
		| 'Дано в Константе "ПутьКVanessaAutomation" указан существующий файл'                                                      | 'ВКонстантеУказанСуществующийФайл'                                                        | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:22'                     | 'Success' | 'ВКонстантеУказанСуществующийФайл(Парам01)'                                                 | 'C:\Commons\rep\vanessa-automation\features\Libraries\VB\step_definitions\ЗапускПростогоСценарияTestClient.epf'         | '13' |
		| 'Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий'                                             | ''                                                                                        | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:23'                     | ''        | ''                                                                                          | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\ОткрытьTestClientExport.feature'                     | '14' |
		| 'Дано Я открыл новый сеанс TestClient или подключил уже существующий'                                                     | 'ЯОткрылНовыйСеансTestClientИлиПодключилУжеСуществующий'                                  | '     C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\ОткрытьTestClientExport.feature:28'                     | 'Success' | 'ЯОткрылНовыйСеансTestClientИлиПодключилУжеСуществующий()'                                  | 'C:\Commons\rep\vanessa-automation\features\Libraries\TestClients\step_definitions\РаботаСTestClient.epf'               | '15' |
		| 'И Я закрыл все окна клиентского приложения'                                                                              | 'ЯЗакрылВсеОкнаКлиентскогоПриложения'                                                     | '     C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\ОткрытьTestClientExport.feature:29'                     | 'Success' | 'ЯЗакрылВсеОкнаКлиентскогоПриложения()'                                                     | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '16' |
		| 'Когда В панели разделов я выбираю "Основная"'                                                                            | 'ВПанелиРазделовЯВыбираю'                                                                 | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:24'                     | 'Success' | 'ВПанелиРазделовЯВыбираю(Парам01)'                                                          | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '17' |
		| 'И В панели функций я выбираю \'Открыть vanessa automation VAEditor\''                                                    | 'ВПанелиФункцийЯВыбираю'                                                                  | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:27'                     | 'Success' | 'ВПанелиФункцийЯВыбираю(Парам01)'                                                           | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '19' |
		| 'Иначе'                                                                                                                   | ''                                                                                        | ''                                                                                                                              | ''        | ''                                                                                          | ''                                                                                                                      | '20' |
		| 'И В панели функций я выбираю "Открыть vanessa automation"'                                                               | 'ВПанелиФункцийЯВыбираю'                                                                  | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:29'                     | ''        | 'ВПанелиФункцийЯВыбираю(Парам01)'                                                           | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '21' |
		| 'Тогда открылось окно "* Vanessa Automation"'                                                                             | 'ОткрылосьОкно'                                                                           | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:31'                     | 'Success' | 'ОткрылосьОкно(Парам01)'                                                                    | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '22' |
		| 'И я фиксирую текущую форму'                                                                                              | 'ЯФиксируюТекущуюФорму'                                                                   | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:32'                     | 'Success' | 'ЯФиксируюТекущуюФорму()'                                                                   | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '23' |
		| 'И я перехожу к закладке с именем "ГруппаНастройки"'                                                                      | 'ЯПерехожуКЗакладкеСИменем'                                                               | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:33'                     | 'Success' | 'ЯПерехожуКЗакладкеСИменем(Парам01)'                                                        | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '24' |
		| 'И В открытой форме я устанавливаю флаг с заголовком "Проверка работы Vanessa-Automation в режиме test client"'           | 'ВОткрытойФормеЯУстанавливаюФлагСЗаголовком'                                              | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:34'                     | 'Success' | 'ВОткрытойФормеЯУстанавливаюФлагСЗаголовком(Парам01)'                                       | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '25' |
		| 'И я перехожу к закладке с именем "ГруппаСлужебная"'                                                                      | 'ЯПерехожуКЗакладкеСИменем'                                                               | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:35'                     | 'Success' | 'ЯПерехожуКЗакладкеСИменем(Парам01)'                                                        | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '26' |
		| 'И В поле с именем "КаталогИнструментовСлужебный" я указываю значение реквизита объекта обработки "КаталогИнструментов"'  | 'ВПолеСИменемЯУказываюЗначениеРеквизитаОбъектаОбработки'                                  | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:36'                     | 'Success' | 'ВПолеСИменемЯУказываюЗначениеРеквизитаОбъектаОбработки(Парам01,Парам02)'                   | 'C:\Commons\rep\vanessa-automation\features\Libraries\VB\step_definitions\ЗапускПростогоСценарияTestClient.epf'         | '27' |
		| 'И я перехожу к закладке с именем "ГруппаНастройки"'                                                                      | 'ЯПерехожуКЗакладкеСИменем'                                                               | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:37'                     | 'Success' | 'ЯПерехожуКЗакладкеСИменем(Парам01)'                                                        | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '28' |
		| 'И я перехожу к закладке "Настройки клиентов тестирования"'                                                               | 'ЯПерехожуКЗакладке'                                                                      | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:38'                     | 'Success' | 'ЯПерехожуКЗакладке(Парам01)'                                                               | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '29' |
		| 'И в поле \'Таймаут запуска клиента тестирования\' я ввожу текст \'20\''                                                  | 'ВПолеЯВвожуТекст'                                                                        | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:39'                     | 'Success' | 'ВПолеЯВвожуТекст(Парам01,Парам02)'                                                         | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '30' |
		| 'И В поле с именем "ДиапазонПортовTestclient" я указываю значение реквизита объекта обработки "ДиапазонПортовTestclient"' | 'ВПолеСИменемЯУказываюЗначениеРеквизитаОбъектаОбработки'                                  | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:40'                     | 'Success' | 'ВПолеСИменемЯУказываюЗначениеРеквизитаОбъектаОбработки(Парам01,Парам02)'                   | 'C:\Commons\rep\vanessa-automation\features\Libraries\VB\step_definitions\ЗапускПростогоСценарияTestClient.epf'         | '31' |
		| 'И я перехожу к закладке с именем "СтраницаСервисОсновные"'                                                               | 'ЯПерехожуКЗакладкеСИменем'                                                               | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:41'                     | 'Success' | 'ЯПерехожуКЗакладкеСИменем(Парам01)'                                                        | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '32' |
		| 'И я отменяю фиксирование формы'                                                                                          | 'ЯОтменяюФиксированиеФормы'                                                               | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытьVanessaBehaviorВTestClient.feature:42'                     | 'Success' | 'ЯОтменяюФиксированиеФормы()'                                                               | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '33' |
		| 'И я перехожу к закладке с именем "ГруппаСлужебная"'                                                                      | 'ЯПерехожуКЗакладкеСИменем'                                                               | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:26' | 'Success' | 'ЯПерехожуКЗакладкеСИменем(Парам01)'                                                        | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '34' |
		| 'И    я снимаю флаг \'Режим самотестирования\''                                                                           | 'ЯСнимаюФлаг'                                                                             | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:27' | 'Success' | 'ЯСнимаюФлаг(Парам01)'                                                                      | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '35' |
		| 'И я перехожу к закладке с именем "ГруппаНастройки"'                                                                      | 'ЯПерехожуКЗакладкеСИменем'                                                               | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:28' | 'Success' | 'ЯПерехожуКЗакладкеСИменем(Парам01)'                                                        | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '36' |
		| 'И я перехожу к закладке с именем "ГруппаЗапускТестов"'                                                                   | 'ЯПерехожуКЗакладкеСИменем'                                                               | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:30' | 'Success' | 'ЯПерехожуКЗакладкеСИменем(Парам01)'                                                        | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '37' |
		| 'И в поле \'Количество попыток выполнения действия\' я ввожу текст \'2\''                                                 | 'ВПолеЯВвожуТекст'                                                                        | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:31' | 'Success' | 'ВПолеЯВвожуТекст(Парам01,Парам02)'                                                         | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '38' |
		| 'И в поле \'Количество секунд поиска окна\' я ввожу текст \'5\''                                                          | 'ВПолеЯВвожуТекст'                                                                        | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:32' | 'Success' | 'ВПолеЯВвожуТекст(Парам01,Парам02)'                                                         | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '39' |
		| 'И я перехожу к закладке с именем "ГруппаСлужебная"'                                                                      | 'ЯПерехожуКЗакладкеСИменем'                                                               | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:34' | 'Success' | 'ЯПерехожуКЗакладкеСИменем(Парам01)'                                                        | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '40' |
		| 'И я перехожу к закладке "Выполнить код"'                                                                                 | 'ЯПерехожуКЗакладке'                                                                      | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:35' | 'Success' | 'ЯПерехожуКЗакладке(Парам01)'                                                               | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '41' |
		| 'И в поле \'Произвольный код\' я ввожу текст'                                                                             | 'ВПолеЯВвожуТекст'                                                                        | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:36' | 'Success' | 'ВПолеЯВвожуТекст(Парам01,ТабПарам)'                                                        | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '42' |
		| '\| \'Объект.ПроверкаРаботыVanessaAutomationВРежимеTestClient = Ложь;\'             \|'                                   | ''                                                                                        | ''                                                                                                                              | ''        | ''                                                                                          | ''                                                                                                                      | '43' |
		| '\| \'ПроверкаРаботыVanessaAutomationВРежимеTestClientПриИзменении(Неопределено);\' \|'                                   | ''                                                                                        | ''                                                                                                                              | ''        | ''                                                                                          | ''                                                                                                                      | '44' |
		| '\| \'УстановитьЗаголовокПриложения("Основной сеанс");\'                            \|'                                   | ''                                                                                        | ''                                                                                                                              | ''        | ''                                                                                          | ''                                                                                                                      | '45' |
		| 'И я нажимаю на кнопку \'Выполнить произвольный код\''                                                                    | 'ЯНажимаюНаКнопку'                                                                        | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:41' | 'Success' | 'ЯНажимаюНаКнопку(Парам01)'                                                                 | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '46' |
		| 'И я перехожу к закладке с именем "ГруппаНастройки"'                                                                      | 'ЯПерехожуКЗакладкеСИменем'                                                               | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:42' | 'Success' | 'ЯПерехожуКЗакладкеСИменем(Парам01)'                                                        | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '47' |
		| 'И я перехожу к закладке с именем "СтраницаСервисОсновные"'                                                               | 'ЯПерехожуКЗакладкеСИменем'                                                               | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:43' | 'Success' | 'ЯПерехожуКЗакладкеСИменем(Парам01)'                                                        | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '48' |
		| 'И я перехожу к закладке с именем "ГруппаКаталогиБиблиотек"'                                                              | 'ЯПерехожуКЗакладкеСИменем'                                                               | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:45' | 'Success' | 'ЯПерехожуКЗакладкеСИменем(Парам01)'                                                        | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '49' |
		| 'И В открытой форме я нажимаю на кнопку с именем "КаталогиБиблиотекДобавить"'                                             | 'ВОткрытойФормеЯНажимаюНаКнопкуСИменем'                                                   | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:46' | 'Success' | 'ВОткрытойФормеЯНажимаюНаКнопкуСИменем(Парам01)'                                            | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '50' |
		| 'И я добавляю в библиотеки строку с стандартной библиотекой "Libraries"'                                                  | 'ЯДобавляюВБиблиотекиСтрокуССтандартнойБиблиотекой'                                       | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:47' | 'Success' | 'ЯДобавляюВБиблиотекиСтрокуССтандартнойБиблиотекой(Парам01)'                                | 'C:\Commons\rep\vanessa-automation\features\Libraries\VB\step_definitions\ЗапускПростогоСценарияTestClient.epf'         | '51' |
		| 'И    В открытой форме я перехожу к закладке "Запуск сценариев"'                                                          | 'ВОткрытойФормеЯПерехожуКЗакладке'                                                        | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:49' | 'Success' | 'ВОткрытойФормеЯПерехожуКЗакладке(Парам01)'                                                 | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '52' |
		| 'И    я нажимаю на кнопку с именем \'ПоказатьСкрытьВсеКолонки\''                                                          | 'ЯНажимаюНаКнопкуСИменем'                                                                 | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:50' | 'Success' | 'ЯНажимаюНаКнопкуСИменем(Парам01)'                                                          | 'C:\Commons\rep\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf'             | '53' |
		| 'И    я запускаю SikuliX сервер'                                                                                          | 'ЯЗапускаюSikuliXСервер'                                                                  | '     C:\Commons\rep\vanessa-automation\features\Libraries\VB\ОткрытиеVanessaBehavoirВTestClientБезЗагрузкиНастроек.feature:51' | 'Success' | 'ЯЗапускаюSikuliXСервер()'                                                                  | 'C:\Commons\rep\vanessa-automation\features\Libraries\SikuliX\SikuliXServer.epf'                                        | '54' |


	

	
	И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ЗакрытьПодключенныйTestClient/ЗакрытьПодключенныйTestClient"

	И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
	И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
Сценарий: Закрыть TestClient
	И я закрываю TestClient "TM"	
	И в таблице клиентов тестирования я активизирую строку 'Этот клиент'


	
Сценарий: Открытие VA для записи автодоков как менеджер тестирования
	Дано Я закрыл все окна клиентского приложения
	И я закрываю сеанс TESTCLIENT
	Когда я запускаю служебный сеанс TestClient с ключом TestManager в той же базе
	
	Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
	
	
	И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ЗаписьАвтодоков/ДляЗаписиАвтодоков02"

	И я перехожу к закладке с именем "ГруппаНастройки"
	И я перехожу к закладке с именем "СтраницаАвтоИнструкции"
	И я разворачиваю группу с именем "ГруппаSikuliXServer"
	И я устанавливаю флаг с именем 'ИспользоватьSikuliXСервер'
	И я нажимаю на кнопку с именем 'КаталогиСкриптовSikuliXПоУмолчанию'
	И я перехожу к закладке с именем "СтраницаВыполнениеСценариев"
	И в поле с именем 'ТаймаутДляАсинхронныхШагов' я ввожу текст '200'
	И я перехожу к следующему реквизиту

	И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
	И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient

	И я выбираю пункт контекстного меню с именем 'ДеревоТестовКонтекстноеМенюСвернутьДоСценариев' на элементе формы с именем "ДеревоТестов"

	Тогда таблица "ДеревоТестов" стала равной:
		| 'Наименование'                 | 'Статус'  |
		| 'ДляЗаписиАвтодоков02.feature' | ''        |
		| 'ДляЗаписиАвтодоков02'         | ''        |
		| 'ДляЗаписиАвтодоков02'         | 'Success' |





	
	И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ЗакрытьПодключенныйTestClient/ЗакрытьПодключенныйTestClient"

	И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
	И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	
Сценарий: Закрыть TestClient
	И я закрываю TestClient "TM"	
	И в таблице клиентов тестирования я активизирую строку 'Этот клиент'